#!/usr/bin/env bash
#Install Nginx web server
#Nginx should listen on port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo /etc/init.d/nginx restart
