#!/usr/bin/env bash
# Install and configure HAProxy Load balancer.
# Requests are distributed using the roundrobin algorithm

sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get install -y haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "
defaults
	mode http

frontend myfrontend
	bind :80
	option forwardfor
	default_backend myservers

backend myservers
	balance roundrobin
	server 37493-web-01 3.235.30.234:80 check
	server 37493-web-02 100.25.177.170: 80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
