#!/usr/bin/env bash
# Using the `if-elif-else` construct.

var="Best School"
a=1

while [ "$a" -le 10 ]
do
  if [ "$a" -eq 4 ]; then
    echo "bad luck"
  elif [ "$a" -eq 8 ]; then
    echo "good luck"
  else
    echo "$var"
  fi
  (( a++ ))
done
